---
driver:
  name: terraform
  root_module_directory: "."

provisioner:
  name: terraform

verifier:
  name: terraform
  systems:
    - name: aws
      backend: aws
      controls:
        - vpc_exists
      inputs:
        vpc_id: "${output.vpc_id}"

platforms:
  - name: aws

suites:
  - name: default
